### ISSUE TITLE
File not found on genbank data example

### ISSUE THREAD

**Issue by bblodfon** [RuslanKhalitov/ChordMixer#1]
Hi Ruslan,

When running step by step the scripts as in [here](https://github.com/RuslanKhalitov/ChordMixer/tree/main/experiments/data#genbank-problem) I run into the following error:
```
FileNotFoundError: [Errno 2] No such file or directory: 'Other vertebrate_df_classes.pkl'
```

This comes from this [code line](https://github.com/RuslanKhalitov/ChordMixer/blob/main/experiments/data/genbank_tax2class.py#L33) - the 'df_classes' pickle files I cannot find them anywhere (nor are generated with the previous scripts?). Did you maybe forgot to upload them or so?

**Comment by Li-fAngyU** [comment]
same issue here

**Comment by RuslanKhalitov** [comment]
Hi, sorry for the long reply. The pre-processing pipeline is multistep and quite heavy. In the new release, we decided to link the datasets we used directly. Please check out ChordMixer/data/download_genbank.py
