### ISSUE TITLE
wrong package in requirement.txt

### ISSUE THREAD

**Issue by keria99** [RuslanKhalitov/ChordMixer#5]
Hi Ruslan,
I got this error when creating the environment using pip with the requirement.txt, seems like a wrong package.

pip install -r requirements.txt

ERROR: Could not find a version that satisfies the requirement screen-resolution-extra==0.0.0 (from versions: none)
ERROR: No matching distribution found for screen-resolution-extra==0.0.0

By the way, which python version did you use?

**Comment by RuslanKhalitov** [comment]
Hi, I used python=3.10.6.
Thank you for your suggestions. I removed the unnecessary packages and versions, please check whether it has resolved the dependency issues.

**Comment by RuslanKhalitov** [comment]
Did it fix the problem?
